MyApp/Controllers/DisplayMessageController.cs
using MyApp.Context;
using MyApp.Entities;
using MyApp.Models;
using MyApp.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyApp.Controllers
{
    [Authorize]
    public class DisplayMessageController : Controller
    {
        public ActionResult Index()
        {
            using (MyAppContext context = new MyAppContext())
            {
                UserRepository repoUser = new UserRepository(context);
                User user = repoUser.getUser(HttpContext.User.Identity.Name);
                MessageRepository repo = new MessageRepository(context);
                List<Message> messages = repo.getAllByName(user.nickName);

                List<Message> alMessages = new List<Message>();
                foreach (Message m in messages)
                {
                    Message model = new Message()
                    {
                        author = m.author,
                        text = m.text
                        
                    };
                    alMessages.Add(model);
                }

                return View(alMessages);
            }

        }
    }
}

MyApp/Controllers/LoginController.cs
using MyApp.Context;
using MyApp.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace MyApp.Controllers
{

    public class LoginController : Controller
    {

        public LoginController()
        {

        }

        public ActionResult Form()
        {
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        
        [HttpPost]
        public ActionResult Form(Models.LoginModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }


            using (MyAppContext context = new MyAppContext())
            {
                UserRepository repo = new UserRepository(context);
                if(repo.CheckUser(model.nickName,model.password))
                {
                    FormsAuthentication.SetAuthCookie(model.nickName, true);
                    return RedirectToAction("Index", "Home");
                } else
                {
                    return View(model);
                }
            }

        } 
        
        [HttpGet]
        public ActionResult Disconnect()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

MyApp/Controllers/MessageController.cs
using MyApp.Context;
using MyApp.Entities;
using MyApp.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyApp.Controllers
{
    [Authorize]
    public class MessageController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(Message model)
        {
            using (MyAppContext context = new MyAppContext())
            {
                UserRepository repoUser = new UserRepository(context);
                MessageRepository repoMessage = new MessageRepository(context);

                User user = repoUser.getUser(HttpContext.User.Identity.Name);
                Message message = new Message()
                {
                    author = user.nickName,
                    text = model.text
                };
                repoMessage.Add(message);
                context.SaveChanges();
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

MyApp/Controllers/RegisterController.cs
using MyApp.Context;
using MyApp.Entities;
using MyApp.Models;
using MyApp.Repositories;
using System;
using System.Web.Mvc;

namespace MyApp.Controllers
{
    public class RegisterController : Controller
    {
        public ActionResult Form()
        {
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        
        [HttpPost]
        public ActionResult Form(User model)
        {

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            using(MyAppContext context = new MyAppContext())
            {
                UserRepository repo = new UserRepository(context);
                User user = new User()
                {
                    lastName = model.lastName,
                    firstName = model.firstName,
                    email = model.email,
                    nickName = model.nickName,
                    password = model.password,
                    verifyPassword = model.verifyPassword

                };
                repo.Add(user);
                context.SaveChanges();
            }

            return RedirectToAction("Form", "Login");
        }
    }
}

MyApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> My App</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <nav class="navbar navbar-expand-sm">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <ul class="navbar-nav">
                            <li class="nav-link">@Html.ActionLink("MyApp", "Index", "Home")</li>
                            <li class="nav-link">@Html.ActionLink("Mon profil", "Index", "Profil")</li>
                            <li class="nav-link">@Html.ActionLink("Mes messages", "Index", "DisplayMessage")</li>
                            <li class="nav-link">@Html.ActionLink("Poster un message", "Index", "Message")</li>
                            <li class="nav-link">@Html.ActionLink("Utilisateurs", "Index", "DisplayUsers")</li>
                        </ul>
                        <ul class="navbar-nav ml-auto">

                            <li class="nav-link userDisplay">@User.Identity.Name</li>
                            <li class="nav-link"><a href="/Login/Disconnect">Deconnexion <i class='fas fa-power-off'></i></a></li>
                        </ul>

                    }
                    else
                    {
                        <ul class="navbar-nav">
                            <li class="nav-link">@Html.ActionLink("MyApp", "Index", "Home")</li>
                            <li class="nav-link">@Html.ActionLink("Créer un compte", "Form", "Register")</li>
                            <li class="nav-link">@Html.ActionLink("Connexion", "Form", "Login")</li>
                        </ul>
                    }
                </div>
            </nav>
        </div>
    </div>


    <div class="container-fluid">
        <div class="row">
            @RenderBody()
        </div>

        <hr />
    </div>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>